#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	/sbin/ifup -a
	ifconfig eth0 192.168.0.20 netmask 255.255.255.0 up
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	mkdir -p /home/vineetg/arc
	mount -o nolock 192.168.0.1:/home/vineetg/arc  /home/vineetg/arc
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

